README.md

I’ll update ❓ for CFP and CoC with proper links once they’re published.

Add pitercss_conf

---

README.md

Add Pacific NW Drupal Summit

---

README.md

Also rearranged some events by date

Add JSConf.Asia and Webconf.asia

---

README.md

Add conference : Blend Web Mix (Lyon, France, October 24-45)

Add conference blendwebmix

---

README.md

Add new conference : Best of Web (Paris, 7-8 June)

Add conf bestofweb

---

README.md

Webconf.asia doesn't have a call for papers

---

README.md

Added a number of Web Directions events from webdirections.org/events

Addition of Web Directions events

---

README.md

Hi, I added all of the South African conferences that I know about, all of them within the next three months. Only one has a CFP open, though.

Added South African conferences for the next 3 months.

---

README.md

Peace,
Just added a conf in South Africa, I hope everything is cool 👊 
Peace

added Pixel Up!

---

README.md

There are [plenty more](https://voxxeddays.com) to add from around the globe

Add Voxxed Days Switzerland

---

README.md

Codeland CFP is closed

---

README.md

Also updated some CFPs that have since closed. Kept a link to the closed page if available.

Add PHP UK Conference and update some CFP statuses

---

README.md

Adding BrazilJS, a conference for 1700 attendees every August for 8 years.

Added BrazilJS

---

README.md

For the moment, it's the 2017 website, the 2018 website will arrive soon

Add DevFest Nantes

---

README.md

Because we don't have a definite date yet.

Remove JSDayES

---

README.md

Django is a popular Python webframework. The DjangoCon Europe 2018 is the 10th European DjangoCon.

add DjangoCon Europe 2018

---

README.md

Add missing US states

---

API.md

Hey just spotted a small typo :) Didn't know until now that you actually made an API for that. That's great!

Fix minor typo

---

README.md

Add Confront, Oct 5

---

README.md

Add CFP & CoC to pitercss_conf

---

README.md

I'm one of the React.NotAConf organizers together w/ @rstankov & @vladimirtassev. We're hosting the first React conference on the Balkans, called [React.NotAConf](http://react-not-a-conf.com/) happening on 28th April in Sofia, Bulgaria. ⚛ 🚀🚀🚀 ⚛

Add React.NotAConf

---

README.md

Sorry, guys, I broke the HTML encoding 😇

Fix HTML encoding

---

README.md

Hi, I would like to add the Web Audio Conf to the list. I tried to follow the style of the document. I only located Berlin in Europe instead of specifically mentioning Germany. I hope that's okay.
Please, let me know if you want me to change something or if you need more infos.

add Web Audio Conf

---

README.md

- Add some informations of the 4th CSSConf in XAmoy(Xiamen), China

Add CSSConf China

---

README.md

Add ScaleConf Colombia

---

README.md

Smashingconf New York and Freiburg added

---

README.md

The Rich web experience conference is taking place in Clearwater, Florida (USA).
@asciidisco please add it to the existing list.
Thanks

added The Rich web experience conference in USA
